Repository wanted-pre-onboarding-frontend-12team/pre-onboarding-7th-2-1-12, pull requests merged in 2022-11, with the labels that each got.

#4 [#3] UI 스타일 구현
  src/App.tsx
  src/assets/images/back_icon.svg
  src/components/feature/DetailForm/index.tsx
  src/components/feature/DetailForm/styled.ts
  src/components/feature/Nav/index.tsx
  src/components/feature/Nav/styled.ts
  src/components/feature/VehicleItem/index.tsx
  src/components/feature/VehicleItem/styled.ts
  src/components/layout/Header/index.tsx
  src/components/layout/Header/styled.ts
  src/components/layout/index.tsx
  src/components/layout/styled.ts
  src/components/shared/Button/index.tsx
  src/components/shared/Button/styled.ts
  src/components/shared/Image/index.tsx
  src/components/shared/Image/styled.ts
  src/pages/CarDetail/index.tsx
  src/pages/CarDetail/styled.ts
  src/pages/CarList/index.tsx
  src/pages/CarList/styled.ts
  src/styles/theme.ts
Labels: ✨ Feature, 💄 UI

#6 [#5] 전역 상태관리, SEO, 데이터 패칭 의존성 패키지 추가 & 프로젝트 Configuration 추가
  .eslintrc.json
  package.json
  src/components/feature/Nav/index.tsx
  src/components/index.ts
  src/components/shared/Button/index.tsx
  src/components/shared/Button/styled.ts
  src/pages/CarList/index.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: ➕ Env

#9 [#7] 에러 바운더리, fallback UI 구현
  src/App.tsx
  src/components/layout/Header/index.tsx
  src/pages/ErrorPage/ErrorBoundary.tsx
  src/pages/ErrorPage/index.tsx
  src/pages/ErrorPage/styled.ts
  src/router/index.tsx
Labels: ✨ Feature, 💄 UI

#12 [#10] 차량 상세 페이지 구현
  src/components/feature/DetailForm/index.tsx
  src/components/feature/DetailForm/styled.ts
  src/components/feature/FormBody/index.tsx
  src/components/feature/FormBody/styled.ts
  src/components/feature/FormHeader/index.tsx
  src/components/feature/FormHeader/styled.ts
  src/hooks/useCar.ts
  src/index.tsx
  src/pages/CarDetail/index.tsx
  src/types/car.ts
Labels: ✨ Feature, 🌐 API

#13 [ #11 ] chip 버튼 관련하여 Recoil을 사용한 상태 관리 Nav, CarItems 관련 UI 작성
  src/components/feature/Nav/index.tsx
  src/components/feature/Nav/styled.ts
  src/components/shared/Chip/index.tsx
  src/components/shared/Chip/styled.ts
  src/constants/attributeDummyData.ts
  src/index.tsx
  src/pages/CarList/index.tsx
  src/pages/CarList/styled.ts
  src/recoil/atoms/ChipAtom.tsx
Labels: ✨ Feature, 💄 UI

#16 [#15] 차량 목록 리스트 컴포넌트 구현
  src/components/feature/CarListItem/index.tsx
  src/components/feature/CarListItem/styled.ts
  src/components/feature/VehicleItem/index.tsx
  src/components/index.ts
  src/constants/car.ts
  src/hooks/useCars.ts
  src/index.tsx
  src/pages/CarList/index.tsx
  src/pages/CarList/styled.ts
  src/router/index.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  src/types/car.ts
  src/utils/ArrayUtils.ts
  src/utils/DateUtils.ts
  src/utils/StringUtils.ts
Labels: ✨ Feature, 🌐 API, 💄 UI

#17 [#8] 충돌 정리/ 메타 태그 수정
  index.html
  src/App.tsx
  src/components/feature/CarListItem/styled.ts
  src/components/feature/VehicleItem/index.tsx
  src/components/shared/SEOMetaTag/index.tsx
  src/index.tsx
  src/pages/CarDetail/index.tsx
  src/pages/CarList/index.tsx
Labels: 💄 UI, 🚑 Bugfix

#25 [#24]
  src/components/shared/Image/styled.ts
  src/pages/CarDetail/index.tsx
  src/pages/CarDetail/styled.ts
Labels: ✨ Feature, 💄 UI

#28 [#26] 요구사항 1차 구현 완료 후, 디테일 수정
  public/_redirects
  src/apis/requester.ts
  src/components/feature/VehicleItem/index.tsx
  src/pages/ErrorPage/styled.ts
Labels: 🔨 Refactor, 🚀 Deploy

#29 [#27] workflow 파일 추가
  .github/workflows/workflow.yml
Labels: 🚀 Deploy

#31 [#30] CSR 환경에서 React-Helmet-Async 를 사용하면서 Open Graph 적용
  src/components/shared/SEOMetaTag/index.tsx
  src/pages/CarDetail/index.tsx
Labels: 🚀 Deploy

#32 Assignment 3 - Release 1.0.0
  .eslintrc.json
  .github/workflows/workflow.yml
  README.md
  index.html
  package.json
  public/_redirects
  public/robots.txt
  src/App.tsx
  src/apis/car.ts
  src/apis/requester.ts
  src/assets/images/back_icon.svg
  src/components/feature/CarListItem/index.tsx
  src/components/feature/CarListItem/styled.ts
  src/components/feature/DetailForm/index.tsx
  src/components/feature/DetailForm/styled.ts
  src/components/feature/FormBody/index.tsx
  src/components/feature/FormBody/styled.ts
  src/components/feature/FormHeader/index.tsx
  src/components/feature/FormHeader/styled.ts
  src/components/feature/Nav/index.tsx
  src/components/feature/Nav/styled.ts
  src/components/index.ts
  src/components/layout/Header/index.tsx
  src/components/layout/Header/styled.ts
  src/components/layout/index.tsx
  src/components/layout/styled.ts
  src/components/shared/Chip/index.tsx
  src/components/shared/Chip/styled.ts
  src/components/shared/Image/index.tsx
  src/components/shared/Image/styled.ts
  src/components/shared/SEOMetaTag/index.tsx
  src/components/shared/StatusContent/index.tsx
  src/components/shared/StatusContent/styled.ts
  src/constants/api.ts
  src/constants/attributeDummyData.ts
  src/constants/car.ts
  src/hooks/useCar.ts
  src/hooks/useCars.ts
  src/index.tsx
  src/pages/CarDetail/index.tsx
  src/pages/CarDetail/styled.ts
  src/pages/CarList/index.tsx
  src/pages/CarList/styled.ts
  src/pages/ErrorPage/ErrorBoundary.tsx
  src/pages/ErrorPage/index.tsx
  src/pages/ErrorPage/styled.ts
  src/recoil/atoms/ChipAtom.tsx
  src/router/index.tsx
  src/styles/GlobalStyle.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
  src/types/car.ts
  src/utils/ArrayUtils.ts
  src/utils/DateUtils.ts
  src/utils/StringUtils.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 🚀 Deploy

#33 Assignment 3 - Release 1.0.1
  .github/workflows/workflow.yml
  README.md
  src/components/layout/Header/styled.ts
  src/pages/CarDetail/styled.ts
  src/pages/CarList/styled.ts
Labels: 💄 UI

#35 Feature/jonghyeon
  src/components/skeleton/SkeletonCarList/SkeletonCarListItem/Index.tsx
  src/components/skeleton/SkeletonCarList/SkeletonCarListItem/styled.ts
  src/components/skeleton/SkeletonCarList/index.tsx
  src/components/skeleton/SkeletonElement/index.tsx
  src/components/skeleton/SkeletonElement/styled.ts
  src/hooks/useCars.ts
  src/pages/CarList/index.tsx
Labels: ✨ Feature, 💄 UI

#36 [#34] STALE_TIME 상수 추가, useCar 컴포넌트 staleTime prop 추가
  src/constants/api.ts
  src/hooks/useCar.ts
  src/pages/CarDetail/index.tsx
Labels: 🐎 Performance, 🔨 Refactor

#37 [#34] Scroll Top 버튼 기능 구현
  src/components/feature/ScrollButton/index.tsx
  src/components/feature/ScrollButton/styled.ts
  src/pages/CarList/index.tsx
Labels: ✨ Feature, 💄 UI, 🔨 Refactor

#38 [#34] 코드 구조, 코드 순서 컨벤션 수정 & 중복되는 코드 컴포넌트 분리 및 불필요한 코드 제거
  README.md
  src/App.tsx
  src/assets/images/back_arrow.svg
  src/components/feature/CarAttributeFilter/index.tsx
  src/components/feature/CarAttributeFilter/styled.ts
  src/components/feature/CarListItem/index.tsx
  src/components/feature/CarListItem/styled.ts
  src/components/feature/CarName/index.tsx
  src/components/feature/CarName/styled.ts
  src/components/feature/DetailForm/FormBody/index.tsx
  src/components/feature/DetailForm/FormBody/styled.ts
  src/components/feature/DetailForm/FormHeader/index.tsx
  src/components/feature/DetailForm/FormHeader/styled.ts
  src/components/feature/DetailForm/index.tsx
  src/components/feature/Nav/index.tsx
  src/components/index.ts
  src/components/layout/Header/index.tsx
  src/components/layout/Header/styled.ts
  src/components/layout/index.tsx
  src/components/shared/Chip/index.tsx
  src/components/shared/Chip/styled.ts
  src/components/shared/Image/index.tsx
  src/components/shared/ImageBackground/index.tsx
  src/components/shared/ImageBackground/styled.ts
  src/components/shared/SEO/index.tsx
  src/constants/car.ts
  src/hooks/useCar.ts
  src/index.tsx
  src/pages/CarDetail/index.tsx
  src/pages/CarDetail/styled.ts
  src/pages/CarList/index.tsx
  src/pages/ErrorPage/ErrorBoundary.tsx
  src/pages/index.ts
  src/recoil/atoms/ChipAtom.tsx
  src/recoil/atoms/carFilter.tsx
  src/router/index.tsx
  src/styles/GlobalStyle.tsx
  src/utils/ArrayUtils.ts
Labels: 🔨 Refactor

#39 Assignment 3 - Release 1.0.2
  README.md
  src/App.tsx
  src/assets/images/back_arrow.svg
  src/components/feature/CarAttributeFilter/index.tsx
  src/components/feature/CarAttributeFilter/styled.ts
  src/components/feature/CarListItem/index.tsx
  src/components/feature/CarListItem/styled.ts
  src/components/feature/CarName/index.tsx
  src/components/feature/CarName/styled.ts
  src/components/feature/DetailForm/FormBody/index.tsx
  src/components/feature/DetailForm/FormBody/styled.ts
  src/components/feature/DetailForm/FormHeader/index.tsx
  src/components/feature/DetailForm/FormHeader/styled.ts
  src/components/feature/DetailForm/index.tsx
  src/components/feature/Nav/index.tsx
  src/components/feature/ScrollButton/index.tsx
  src/components/feature/ScrollButton/styled.ts
  src/components/index.ts
  src/components/layout/Header/index.tsx
  src/components/layout/Header/styled.ts
  src/components/layout/index.tsx
  src/components/shared/Chip/index.tsx
  src/components/shared/Chip/styled.ts
  src/components/shared/Image/index.tsx
  src/components/shared/ImageBackground/index.tsx
  src/components/shared/ImageBackground/styled.ts
  src/components/shared/SEO/index.tsx
  src/components/skeleton/SkeletonCarList/SkeletonCarListItem/Index.tsx
  src/components/skeleton/SkeletonCarList/SkeletonCarListItem/styled.ts
  src/components/skeleton/SkeletonCarList/index.tsx
  src/components/skeleton/SkeletonElement/index.tsx
  src/components/skeleton/SkeletonElement/styled.ts
  src/constants/api.ts
  src/constants/car.ts
  src/hooks/useCar.ts
  src/hooks/useCars.ts
  src/index.tsx
  src/pages/CarDetail/index.tsx
  src/pages/CarDetail/styled.ts
  src/pages/CarList/index.tsx
  src/pages/ErrorPage/ErrorBoundary.tsx
  src/pages/index.ts
  src/recoil/atoms/ChipAtom.tsx
  src/recoil/atoms/carFilter.tsx
  src/router/index.tsx
  src/styles/GlobalStyle.tsx
  src/utils/ArrayUtils.ts
Labels: ✨ Feature, 🎨 Structure, 💄 UI, 🔨 Refactor
